### ISSUE TITLE
No output from display

### ISSUE THREAD

**Issue by hamishfagg** [Spritetm/picframe_colepd#1]
Hi there,
I'm attempting to build one of these, thank you so much for the design!

I had the boards made by JLC, and I have the firmware working fine, downloading images etc. But the screen never flickers or displays anything - just stays white.
Do you have any idea what this could be? The logs from the firmware are below, in case the gpio output is of use:

```
I (3753) sync: Sync done.
I (4113) main: Displaying img id 8 from slot 7
I (4113) gpio: GPIO[5]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (4113) gpio: GPIO[6]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (4123) gpio: GPIO[4]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (5433) epd: Displayed image.
I (5433) gpio: GPIO[5]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (5443) gpio: GPIO[6]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (5443) gpio: GPIO[7]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (5453) gpio: GPIO[8]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (5463) gpio: GPIO[9]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (5473) main: Going to sleep.
```

There's output from the ESP32 on SCL and SDA when its writing image data, and the screen has 3.3V where it should, so Im not sure what's wrong

**Comment by Spritetm** [comment]
That could be a lot of things, and generally the screen doesn't give much feedback. The only line back is the BUSY line; can you check if that ever goes to 0 for a few ms, or does it stay at 1?

**Comment by hamishfagg** [comment]
Well this is embarrassing - I took another look at the PCB and realised I had got the wrong ribbon connectors installed on the PCB, bottom contacts instead of top.
So I've ordered the right ones, I'll close this assuming it'll work when the screen is actually connected lol

**Comment by Spritetm** [comment]
That'll do it indeed :) if you still run into issues (and/or if you succesfully built yours!) feel free to open a new issue or send me a message.
